cc_library(
    name = "support",
    srcs = [],
    hdrs = ["support.h"],
)

cc_binary(
    name = "support_main",
    srcs = ["support_main.cpp",],
    deps = ["//support:support"],
    data = ["example.txt",],
)